package com.example.demo;

public class AniinbResponse {

	public static String getAniinbResponse(String lastNumer) {
		String result ="";
		if("2".equals(lastNumer)) {
			result=
					"<Tx>\r\n" + 
					"   <TxHead>\r\n" + 
					"      <CTF_A_TXN_LEN>0116</CTF_A_TXN_LEN>\r\n" + 
					"      <CTF_A_TXN_ID_CODE>AIINB</CTF_A_TXN_ID_CODE>\r\n" + 
					"      <CTF_A_TXN_CHANNEL>AI</CTF_A_TXN_CHANNEL>\r\n" + 
					"      <CTF_A_HOST_SEQ_NO>000000</CTF_A_HOST_SEQ_NO>\r\n" + 
					"      <CTF_A_STAN_NO>10300066645</CTF_A_STAN_NO>\r\n" + 
					"      <CTF_A_TXN_DATE>20200730</CTF_A_TXN_DATE>\r\n" + 
					"      <CTF_A_TXN_TIME>180746</CTF_A_TXN_TIME>\r\n" + 
					"      <CTF_A_TERM_ID>MB887200</CTF_A_TERM_ID>\r\n" + 
					"      <CTF_A_BUSI_DATE>20200730</CTF_A_BUSI_DATE>\r\n" + 
					"      <CTF_A_ATMP_MODE>0</CTF_A_ATMP_MODE>\r\n" + 
					"      <CTF_A_FISC_MODE>0</CTF_A_FISC_MODE>\r\n" + 
					"      <CTF_A_RTN_CODE>0000</CTF_A_RTN_CODE>\r\n" + 
					"      <CTF_A_SEND_BANK>1030000</CTF_A_SEND_BANK>\r\n" + 
					"      <CTF_A_RECV_BANK>1030000</CTF_A_RECV_BANK>\r\n" + 
					"      <CTF_A_FILLER />\r\n" + 
					"      <CLIENT_IP />\r\n"+
					"      <SERVER_IP />\r\n"+
					"      <VERSION />\r\n"+
					"   </TxHead>\r\n" + 
					"   <TxBody>\r\n" + 
					"      <CUS_IDN>Y100736961</CUS_IDN>\r\n" + 
					"      <IPMSET_CODE>234234234234</IPMSET_CODE>\r\n" + 
					"      <TRAN_TYPE />\r\n" + 
					"      <QRY_START_DATE>20200702</QRY_START_DATE>\r\n" + 
					"      <QRY_END_DATE>20200710</QRY_END_DATE>\r\n" + 
					"      <LAST_NUMBER>2</LAST_NUMBER>\r\n" + 
					"      <END_KEY>END</END_KEY>\r\n" + 
					"      <TxRepeat> \r\n" + 
					"          <IPMSET_CODE>TEST3</IPMSET_CODE>\r\n" + 
					"          <REF_NO>TEST123456</REF_NO>\r\n" + 
					"          <TRUST_TYPE>1</TRUST_TYPE>\r\n" + 
					"          <TRAN_TYPE>10</TRAN_TYPE>\r\n" + 
					"          <BANK_PRO_CODE>4307</BANK_PRO_CODE>\r\n" + 
					"          <TX_DATE>20200731</TX_DATE>\r\n" + 
					"          <TX_CCY>NTD</TX_CCY>\r\n" + 
					"          <INV_AMT_FC>000000000111155</INV_AMT_FC>\r\n" + 
					"          <PRICE>0011116666</PRICE>\r\n" + 
					"          <FX_RATE>00000000333</FX_RATE>\r\n" + 
					"          <WITHDRAW_AC_NO>123456789987564325</WITHDRAW_AC_NO>\r\n" + 
					"          <REDEM_AC_NO>787878786544454</REDEM_AC_NO>\r\n" + 
					"          <TRAN_STATUS>1</TRAN_STATUS>\r\n" + 
					"          <UNIT>000000066666</UNIT>\r\n" + 
					"          <SELL_AMT>00000000077777</SELL_AMT>\r\n" + 
					"          <SHORT_TERM_FEE>00000000088888</SHORT_TERM_FEE>\r\n" + 
					"          <RBL_YN>N</RBL_YN>\r\n" + 
					"          <DIVIDEND_RATE>00001110000</DIVIDEND_RATE>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT>0000111000</DIVIDEND_AMT_PER_UNIT>\r\n" + 
					"      </TxRepeat>\r\n" + 
					"      <TxRepeat> \r\n" + 
					"          <IPMSET_CODE>TEST4</IPMSET_CODE>\r\n" + 
					"          <REF_NO>TEST1dsf6</REF_NO>\r\n" + 
					"          <TRUST_TYPE>1</TRUST_TYPE>\r\n" + 
					"          <TRAN_TYPE>20</TRAN_TYPE>\r\n" + 
					"          <BANK_PRO_CODE>1208</BANK_PRO_CODE>\r\n" + 
					"          <TX_DATE>20200731</TX_DATE>\r\n" + 
					"          <TX_CCY>TWD</TX_CCY>\r\n" + 
					"          <INV_AMT_FC>000000000111155</INV_AMT_FC>\r\n" + 
					"          <PRICE>0011116666</PRICE>\r\n" + 
					"          <FX_RATE>00000000333</FX_RATE>\r\n" + 
					"          <WITHDRAW_AC_NO>123456789987564325</WITHDRAW_AC_NO>\r\n" + 
					"          <REDEM_AC_NO>787878786544454</REDEM_AC_NO>\r\n" + 
					"          <TRAN_STATUS>1</TRAN_STATUS>\r\n" + 
					"          <UNIT>000000066666</UNIT>\r\n" + 
					"          <SELL_AMT>00000000077777</SELL_AMT>\r\n" + 
					"          <SHORT_TERM_FEE>00000000088888</SHORT_TERM_FEE>\r\n" + 
					"          <RBL_YN>N</RBL_YN>\r\n" + 
					"          <DIVIDEND_RATE>00001110000</DIVIDEND_RATE>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT>0000111000</DIVIDEND_AMT_PER_UNIT>\r\n" + 
					"      </TxRepeat>\r\n" + 
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"   </TxBody>\r\n" + 
					"</Tx>";
		}else {
			result ="<Tx>\r\n" + 
					"   <TxHead>\r\n" + 
					"      <CTF_A_TXN_LEN>0116</CTF_A_TXN_LEN>\r\n" + 
					"      <CTF_A_TXN_ID_CODE>AIINB</CTF_A_TXN_ID_CODE>\r\n" + 
					"      <CTF_A_TXN_CHANNEL>AI</CTF_A_TXN_CHANNEL>\r\n" + 
					"      <CTF_A_HOST_SEQ_NO>000000</CTF_A_HOST_SEQ_NO>\r\n" + 
					"      <CTF_A_STAN_NO>10300066645</CTF_A_STAN_NO>\r\n" + 
					"      <CTF_A_TXN_DATE>20200730</CTF_A_TXN_DATE>\r\n" + 
					"      <CTF_A_TXN_TIME>180746</CTF_A_TXN_TIME>\r\n" + 
					"      <CTF_A_TERM_ID>MB887200</CTF_A_TERM_ID>\r\n" + 
					"      <CTF_A_BUSI_DATE>20200730</CTF_A_BUSI_DATE>\r\n" + 
					"      <CTF_A_ATMP_MODE>0</CTF_A_ATMP_MODE>\r\n" + 
					"      <CTF_A_FISC_MODE>0</CTF_A_FISC_MODE>\r\n" + 
					"      <CTF_A_RTN_CODE>0000</CTF_A_RTN_CODE>\r\n" + 
					"      <CTF_A_SEND_BANK>1030000</CTF_A_SEND_BANK>\r\n" + 
					"      <CTF_A_RECV_BANK>1030000</CTF_A_RECV_BANK>\r\n" + 
					"      <CTF_A_FILLER />\r\n" + 
					"      <CLIENT_IP />\r\n"+
					"      <SERVER_IP />\r\n"+
					"      <VERSION />\r\n"+
					"   </TxHead>\r\n" + 
					"   <TxBody>\r\n" + 
					"      <CUS_IDN>Y100736961</CUS_IDN>\r\n" + 
					"      <IPMSET_CODE>234234234234</IPMSET_CODE>\r\n" + 
					"      <TRAN_TYPE />\r\n" + 
					"      <QRY_START_DATE>20200702</QRY_START_DATE>\r\n" + 
					"      <QRY_END_DATE>20200710</QRY_END_DATE>\r\n" + 
					"      <LAST_NUMBER>2</LAST_NUMBER>\r\n" + 
					"      <END_KEY/>\r\n" + 
					"      <TxRepeat> \r\n" + 
					"          <IPMSET_CODE>TEST1</IPMSET_CODE>\r\n" + 
					"          <REF_NO>TEST123456</REF_NO>\r\n" + 
					"          <TRUST_TYPE>1</TRUST_TYPE>\r\n" + 
					"          <TRAN_TYPE>10</TRAN_TYPE>\r\n" + 
					"          <BANK_PRO_CODE>4307</BANK_PRO_CODE>\r\n" + 
					"          <TX_DATE>20200731</TX_DATE>\r\n" + 
					"          <TX_CCY>TWD</TX_CCY>\r\n" + 
					"          <INV_AMT_FC>000000000111155</INV_AMT_FC>\r\n" + 
					"          <PRICE>0011116666</PRICE>\r\n" + 
					"          <FX_RATE>00000000333</FX_RATE>\r\n" + 
					"          <WITHDRAW_AC_NO>123456789987564325</WITHDRAW_AC_NO>\r\n" + 
					"          <REDEM_AC_NO>787878786544454</REDEM_AC_NO>\r\n" + 
					"          <TRAN_STATUS>1</TRAN_STATUS>\r\n" + 
					"          <UNIT>000000066666</UNIT>\r\n" + 
					"          <SELL_AMT>00000000077777</SELL_AMT>\r\n" + 
					"          <SHORT_TERM_FEE>00000000088888</SHORT_TERM_FEE>\r\n" + 
					"          <RBL_YN>N</RBL_YN>\r\n" + 
					"          <DIVIDEND_RATE>00001110000</DIVIDEND_RATE>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT>0000111000</DIVIDEND_AMT_PER_UNIT>\r\n" + 
					"      </TxRepeat>\r\n" + 
					"      <TxRepeat> \r\n" + 
					"          <IPMSET_CODE>TEST2</IPMSET_CODE>\r\n" + 
					"          <REF_NO>TEST1dsf6</REF_NO>\r\n" + 
					"          <TRUST_TYPE>1</TRUST_TYPE>\r\n" + 
					"          <TRAN_TYPE>20</TRAN_TYPE>\r\n" + 
					"          <BANK_PRO_CODE>1208</BANK_PRO_CODE>\r\n" + 
					"          <TX_DATE>20200731</TX_DATE>\r\n" + 
					"          <TX_CCY>TWD</TX_CCY>\r\n" + 
					"          <INV_AMT_FC>000000000111155</INV_AMT_FC>\r\n" + 
					"          <PRICE>0011116666</PRICE>\r\n" + 
					"          <FX_RATE>00000000333</FX_RATE>\r\n" + 
					"          <WITHDRAW_AC_NO>123456789987564325</WITHDRAW_AC_NO>\r\n" + 
					"          <REDEM_AC_NO>787878786544454</REDEM_AC_NO>\r\n" + 
					"          <TRAN_STATUS>1</TRAN_STATUS>\r\n" + 
					"          <UNIT>000000066666</UNIT>\r\n" + 
					"          <SELL_AMT>00000000077777</SELL_AMT>\r\n" + 
					"          <SHORT_TERM_FEE>00000000088888</SHORT_TERM_FEE>\r\n" + 
					"          <RBL_YN>N</RBL_YN>\r\n" + 
					"          <DIVIDEND_RATE>00001110000</DIVIDEND_RATE>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT>0000111000</DIVIDEND_AMT_PER_UNIT>\r\n" + 
					"      </TxRepeat>\r\n" + 
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"      <TxRepeat>\r\n" + 
					"          <IPMSET_CODE/>\r\n" + 
					"          <REF_NO/>\r\n" + 
					"      	   <TRUST_TYPE/>\r\n" + 
					"      	   <TRAN_TYPE/>\r\n" + 
					"          <BANK_PRO_CODE/>\r\n" + 
					"          <TX_DATE/>\r\n" + 
					"          <TX_CCY/>\r\n" + 
					"          <INV_AMT_FC/>\r\n" + 
					"          <PRICE/>\r\n" + 
					"          <FX_RATE/>\r\n" + 
					"          <WITHDRAW_AC_NO/>\r\n" + 
					"          <REDEM_AC_NO/>\r\n" + 
					"          <TRAN_STATUS/>\r\n" + 
					"          <UNIT/>\r\n" + 
					"          <SELL_AMT/>\r\n" + 
					"          <SHORT_TERM_FEE/>\r\n" + 
					"          <RBL_YN/>\r\n" + 
					"          <DIVIDEND_RATE/>\r\n" + 
					"          <DIVIDEND_AMT_PER_UNIT/>\r\n" + 
					"      </TxRepeat>\r\n"+
					"   </TxBody>\r\n" + 
					"</Tx>   ";
		}
		
		
		return result;
	}
}
