package com.example.demo;

public class N1010Response {
	
	public static String getResponse() {
		StringBuilder sb = new StringBuilder();
		sb.append(" <Tx> ");
		sb.append("     <TxHead> ");
		sb.append("         <CTF_A_TXN_LEN>1425</CTF_A_TXN_LEN> ");
		sb.append("         <CTF_A_TXN_ID_CODE>N1011</CTF_A_TXN_ID_CODE> ");
		sb.append("         <CTF_A_TXN_CHANNEL>WM</CTF_A_TXN_CHANNEL> ");
		sb.append("         <CTF_A_HOST_SEQ_NO>0000158</CTF_A_HOST_SEQ_NO> ");
		sb.append("         <CTF_A_STAN_NO>1030000000</CTF_A_STAN_NO> ");
		sb.append("         <CTF_A_TXN_DATE>20220106</CTF_A_TXN_DATE> ");
		sb.append("         <CTF_A_TXN_TIME>120934</CTF_A_TXN_TIME> ");
		sb.append("         <CTF_A_TERM_ID>MB887221</CTF_A_TERM_ID> ");
		sb.append("         <CTF_A_BUSI_DATE>20220106</CTF_A_BUSI_DATE> ");
		sb.append("         <CTF_A_ATMP_MODE>0</CTF_A_ATMP_MODE> ");
		sb.append("         <CTF_A_FISC_MODE>0</CTF_A_FISC_MODE> ");
		sb.append("         <CTF_A_RTN_CODE>0000</CTF_A_RTN_CODE> ");
		sb.append("         <CTF_A_SEND_BANK>1030000</CTF_A_SEND_BANK> ");
		sb.append("         <CTF_A_RECV_BANK>1030000</CTF_A_RECV_BANK> ");
		sb.append("         <CTF_A_FILLER/> ");
		sb.append("     </TxHead> ");
		sb.append("     <TxBody> ");
		sb.append("         <WMSG_ID_NO>A121346968</WMSG_ID_NO> ");
		sb.append("         <WMSG_CUST_NAME>測試帳戶</WMSG_CUST_NAME> ");
		sb.append("         <WMSG_CUST_ENG_NAME></WMSG_CUST_ENG_NAME> ");
		sb.append("         <WMSG_SEX_CODE/> ");
		sb.append("         <WMSG_INQ_INDEX/> ");
		sb.append("         <WMSG_COUNT>05</WMSG_COUNT> ");
		sb.append("         <TxRepeat> ");
		sb.append("             <WMSG_ACC_ID_NO>0000019110322514</WMSG_ACC_ID_NO> ");
		sb.append("             <WMSG_BR_CODE>1012</WMSG_BR_CODE> ");
		sb.append("             <WMSG_CURR_CODE>AUD</WMSG_CURR_CODE> ");
		sb.append("             <WMSG_PRD_CODE>F500002</WMSG_PRD_CODE> ");
		sb.append("             <WMSG_ACC_STAT>00</WMSG_ACC_STAT> ");
		sb.append("             <WMSG_AVAIL_BAL_SIGN>+</WMSG_AVAIL_BAL_SIGN> ");
		sb.append("             <WMSG_AVAIL_BAL>0000000037711</WMSG_AVAIL_BAL> ");
		sb.append("             <WMSG_BAL_SIGN>+</WMSG_BAL_SIGN> ");
		sb.append("             <WMSG_BAL>0000000037711</WMSG_BAL> ");
		sb.append("             <WMSG_NB_TRAN>1</WMSG_NB_TRAN> ");
		sb.append("             <WMSG_MS_FLAG>0</WMSG_MS_FLAG> ");
		sb.append("         </TxRepeat> ");
		sb.append("         <TxRepeat> ");
		sb.append("             <WMSG_ACC_ID_NO>0000019110322513</WMSG_ACC_ID_NO> ");
		sb.append("             <WMSG_BR_CODE>1012</WMSG_BR_CODE> ");
		sb.append("             <WMSG_CURR_CODE/> ");
		sb.append("             <WMSG_PRD_CODE>F400001</WMSG_PRD_CODE> ");
		sb.append("             <WMSG_ACC_STAT>00</WMSG_ACC_STAT> ");
		sb.append("             <WMSG_AVAIL_BAL_SIGN/> ");
		sb.append("             <WMSG_AVAIL_BAL>0000000000000</WMSG_AVAIL_BAL> ");
		sb.append("             <WMSG_BAL_SIGN/> ");
		sb.append("             <WMSG_BAL>0000000000000</WMSG_BAL> ");
		sb.append("             <WMSG_NB_TRAN>0</WMSG_NB_TRAN> ");
		sb.append("             <WMSG_MS_FLAG>1</WMSG_MS_FLAG> ");
		sb.append("         </TxRepeat> ");
		sb.append("         <TxRepeat> ");
		sb.append("             <WMSG_ACC_ID_NO>0000019110322513</WMSG_ACC_ID_NO> ");
		sb.append("             <WMSG_BR_CODE>1012</WMSG_BR_CODE> ");
		sb.append("             <WMSG_CURR_CODE>JPY</WMSG_CURR_CODE> ");
		sb.append("             <WMSG_PRD_CODE>F500002</WMSG_PRD_CODE> ");
		sb.append("             <WMSG_ACC_STAT>00</WMSG_ACC_STAT> ");
		sb.append("             <WMSG_AVAIL_BAL_SIGN>+</WMSG_AVAIL_BAL_SIGN> ");
		sb.append("             <WMSG_AVAIL_BAL>0000200001300</WMSG_AVAIL_BAL> ");
		sb.append("             <WMSG_BAL_SIGN>+</WMSG_BAL_SIGN> ");
		sb.append("             <WMSG_BAL>0000200001300</WMSG_BAL> ");
		sb.append("             <WMSG_NB_TRAN>0</WMSG_NB_TRAN> ");
		sb.append("             <WMSG_MS_FLAG>0</WMSG_MS_FLAG> ");
		sb.append("         </TxRepeat> ");
		sb.append("         <TxRepeat> ");
		sb.append("             <WMSG_ACC_ID_NO>0000019110322513</WMSG_ACC_ID_NO> ");
		sb.append("             <WMSG_BR_CODE>1012</WMSG_BR_CODE> ");
		sb.append("             <WMSG_CURR_CODE>USD</WMSG_CURR_CODE> ");
		sb.append("             <WMSG_PRD_CODE>F500002</WMSG_PRD_CODE> ");
		sb.append("             <WMSG_ACC_STAT>00</WMSG_ACC_STAT> ");
		sb.append("             <WMSG_AVAIL_BAL_SIGN>+</WMSG_AVAIL_BAL_SIGN> ");
		sb.append("             <WMSG_AVAIL_BAL>4999989280480</WMSG_AVAIL_BAL> ");
		sb.append("             <WMSG_BAL_SIGN>+</WMSG_BAL_SIGN> ");
		sb.append("             <WMSG_BAL>5000001395368</WMSG_BAL> ");
		sb.append("             <WMSG_NB_TRAN>0</WMSG_NB_TRAN> ");
		sb.append("             <WMSG_MS_FLAG>0</WMSG_MS_FLAG> ");
		sb.append("         </TxRepeat> ");
		sb.append("         <TxRepeat> ");
		sb.append("             <WMSG_ACC_ID_NO>0000019110322513</WMSG_ACC_ID_NO> ");
		sb.append("             <WMSG_BR_CODE>1012</WMSG_BR_CODE> ");
		sb.append("             <WMSG_CURR_CODE>ZAR</WMSG_CURR_CODE> ");
		sb.append("             <WMSG_PRD_CODE>F500002</WMSG_PRD_CODE> ");
		sb.append("             <WMSG_ACC_STAT>00</WMSG_ACC_STAT> ");
		sb.append("             <WMSG_AVAIL_BAL_SIGN>+</WMSG_AVAIL_BAL_SIGN> ");
		sb.append("             <WMSG_AVAIL_BAL>0000048555976</WMSG_AVAIL_BAL> ");
		sb.append("             <WMSG_BAL_SIGN>+</WMSG_BAL_SIGN> ");
		sb.append("             <WMSG_BAL>0000060355974</WMSG_BAL> ");
		sb.append("             <WMSG_NB_TRAN>0</WMSG_NB_TRAN> ");
		sb.append("             <WMSG_MS_FLAG>0</WMSG_MS_FLAG> ");
		sb.append("         </TxRepeat> ");
		sb.append("     </TxBody> ");
		sb.append(" </Tx> ");
		return sb.toString();
	}

}
